---
- name: Create servers with public IPs
  hetzner.hcloud.server:
    name: "{{ db_server_name }}-{{ item }}"
    server_type: "{{ db_server_type }}"
    image: "{{ hcloud_image }}"
    location: "{{ hcloud_location }}"
    enable_ipv4: true
    enable_ipv6: false
    private_networks : 
      - "{{ db_network_name }}"
    firewalls : 
      - "{{ db_cluster_firewall_name }}"
    ssh_keys: "{{ ssh_keys | map(attribute='name') | list }}"
    
    state: present
  loop: "{{ range(1, db_server_count | int + 1) | list }}"
