---
- name: Configure pg_hba.conf for allowed networks
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    line: "host    all             all             {{ item }}              trust"
    state: present
  loop: "{{ pg_allowed_networks }}"


- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
    enabled: yes


- name: Create Citus extension
  become_user: postgres
  postgresql_ext:
    name: citus
    db: postgres