---
- name: Configure pg_hba.conf using template
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgres_version }}/main/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0640'
    backup: yes


- name: Set wal_level to logical in postgresql.conf
  lineinfile:
    path: "/etc/postgresql/{{ postgres_version }}/main/postgresql.conf"
    regexp: '^#?wal_level\s*='
    line: 'wal_level = logical'
    backup: yes

- name: Restart PostgreSQL
  service:
    name: postgresql
    state: restarted
    enabled: yes


- name: Create Citus extension
  become_user: postgres
  postgresql_ext:
    name: citus
    db: postgres