---
- name: Set coordinator host
  become_user: postgres
  postgresql_query:
    query: "SELECT citus_set_coordinator_host('{{ ansible_hostname }}', {{ postgres_port }});"
    db: postgres


- name: Add worker nodes
  become_user: postgres
  postgresql_query:
    query: "SELECT * FROM citus_add_node('{{ item.host }}', {{ item.port }});"
    db: postgres
  loop: "{{ worker_nodes }}"



- name: Verify worker nodes
  become_user: postgres
  postgresql_query:
    query: "SELECT * FROM citus_get_active_worker_nodes();"
    db: postgres