---
- name: Wait for PostgreSQL to be ready
  wait_for:
    port: "{{ postgresql_port }}"
    host: "127.0.0.1"
    timeout: 30
  become: true

- name: Create Citus extension
  postgresql_ext:
    name: citus
    db: "{{ citus_database }}"
    port: "{{ postgresql_port }}"
  become: true
  become_user: postgres