---


- name: Show simple message
  debug:
    msg: "Installing PostgreSQL and Citus"

- name: Add Citus repository
  shell: curl https://install.citusdata.com/community/deb.sh | bash
  args:
    executable: /bin/bash


- name: Install PostgreSQL and Citus
  apt:
    name: "postgresql-{{ postgres_version }}-citus-{{ citus_version }}"
    state: present
    update_cache: yes

- name: Enable Citus in shared_preload_libraries
  shell: pg_conftool {{ postgres_version }} main set shared_preload_libraries citus


- name: Set listen_addresses
  shell: pg_conftool {{ postgres_version }} main set listen_addresses '{{ postgres_listen_addresses }}'