---
# tasks file for db-citus

- name: Include tasks of installation
  include_tasks: install.yml

- name: Include tasks of configuration
  include_tasks: configure.yml

- name: Include tasks of coordinator setup
  include_tasks: coordinator.yml

- name: Include tasks of user management
  include_tasks: users.yml
